
image:
  file: .gitpod.Dockerfile

ports:
  # Rails server
  - port: 3000
    onOpen: ignore
  # Hot reload server (not currently in use due to gitpod tcp port challenges)
  - port: 3035
    onOpen: ignore
    visibility: private
  # PostgreSQL server
  - port: 5432
    onOpen: ignore
    visibility: private

tasks:
  - init: |
      bash .gp/bash/init.sh
  - openMode: split-right
    command: |
      bash .gp/bash/ready.sh

vscode:
  extensions:
    - rebornix.ruby
